Disable AboutHtmlCheck (#335)
* Disable AboutHtmlCheck

Removes the AboutHtmlCheck check from the rules.xml because it is no longer used now all openHAB repositories are also moving to EPL-2.0.

Fixes the following exception during builds:

java.io.IOException: Unable to get https://raw.githubusercontent.com/openhab/openhab2-addons/master/src/etc/about.html

Signed-off-by: Wouter Born <eclipse@maindrain.net>